# Run this Jupyter Notebook to get all the data and store it locally.

In [1]:
import pandas as pd
from pandas.tseries.offsets import MonthEnd, YearEnd
from datetime import datetime
from dateutil.relativedelta import relativedelta

import numpy as np
import wrds

import config
from pathlib import Path

import load_wrds
import misc_tools
import load_fm_factors

import warnings
warnings.filterwarnings("ignore")

In [2]:
crsp = load_wrds.pull_CRSP_stock()
comp = load_wrds.pull_compustat()
ccm = load_wrds.pull_CRSP_Comp_Link_Table()

merged = load_fm_factors.merge_crsp_com(crsp, comp, ccm)
merged_final = load_fm_factors.fm_factors(merged)

Loading library list...
Done
Loading library list...
Done
Loading library list...
Done

In [3]:
# store data in relative filepath folder as seen below as parquet files
load_wrds.save_compustat(comp)
load_wrds.save_crsp(crsp)
load_wrds.save_linktbl(ccm)
load_wrds.save_merge(merged_final)

DataFrame saved to /Users/kaiwentay/Documents/GitHub/FINM-32900---Final-Project/data/pulled/Compustat.parquet
DataFrame saved to /Users/kaiwentay/Documents/GitHub/FINM-32900---Final-Project/data/pulled/Crsp.parquet
DataFrame saved to /Users/kaiwentay/Documents/GitHub/FINM-32900---Final-Project/data/pulled/LinkTbl.parquet
DataFrame saved to /Users/kaiwentay/Documents/GitHub/FINM-32900---Final-Project/data/pulled/Merge.parquet

0

In [4]:
merged_final

,gvkey,permno,date,datadate,fyear,sales,earnings,assets,accruals,non_cash_current_assets,...,rolling_beta,logsize-1,logB/M-1,ret-2-12,logissues-1-36,DY-1-12,logret-13-36,logissues-1-12,debt/price_yr-1,sales/price_yr-1
0,1000,25881,1970-11-30,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.760217,8.090709,NaN,-0.303030,NaN,0.0,NaN,0.000000,NaN,NaN
1,1000,25881,1970-12-31,1970-12-31,1970.0,45.335,0.558,33.450,-1.256,19.691,...,-0.031980,11.445725,-7.935673,-0.018692,0.001183,0.0,-0.092659,-0.017003,0.000142,0.000485
2,1000,25881,1971-01-31,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.516609,10.846169,NaN,0.451613,0.001185,0.0,0.039221,0.007123,NaN,NaN
3,1000,25881,1971-02-28,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.458686,13.457935,NaN,0.138138,0.000688,0.0,-0.090846,0.001874,NaN,NaN
4,1000,25881,1971-03-31,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.257189,10.311142,NaN,-0.264706,0.000999,0.0,0.087011,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4612727,350681,22205,2021-12-31,2021-12-31,2021.0,512.094,85.469,10595.813,-182.520,9866.118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612745,351038,16161,2021-12-31,2021-12-31,2021.0,0.000,-21.463,9.357,-7.789,1.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612757,351038,16161,2022-12-31,2022-12-31,2022.0,0.000,-9.381,14.458,-3.116,0.516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612791,353444,23209,2022-12-31,2022-12-31,2022.0,13082.804,1277.194,41948.594,-1544.682,4066.537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612817,354003,23698,2023-12-31,2023-12-31,2023.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN