# Run this Jupyter Notebook to get all the data and store it locally.

In [1]:
import load_wrds
import config
from pathlib import Path
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

OUTPUT_DIR = Path(config.OUTPUT_DIR)
DATA_DIR = Path(config.DATA_DIR)
WRDS_USERNAME = config.WRDS_USERNAME

In [22]:
mngrdata = load_wrds.load_13f()

Loading library list...
Done

In [23]:
# store data in relative filepath folder as seen below as parquet files
mngrdata.to_parquet(DATA_DIR / "Pulled" / "mngrdata.parquet")

In [24]:
mngrdata

,cik,coname,form,rdate,fdate,fname,nameofissuer,titleofclass,cusip,value,sshprnamt,sshprnamttype,putcall,investmentdiscretion,othermanager,sole,shared,none
0,0000814375,"DONALD SMITH & CO., INC.",13F-HR,2013-06-30,2013-08-14,edgar/data/814375/0000814375-13-000043.txt,ADVANTAGE OIL AND GAS,COM,00765F101,63687.0,16164160.0,SH,None,SOLE,0,12351380.0,0.0,0.0
1,0000814375,"DONALD SMITH & CO., INC.",13F-HR,2013-06-30,2013-08-14,edgar/data/814375/0000814375-13-000043.txt,AIR FRANCE-KLM,COM,009119108,142792.0,15778152.0,SH,None,DFND,2,0.0,7717947.0,0.0
2,0000814375,"DONALD SMITH & CO., INC.",13F-HR,2013-06-30,2013-08-14,edgar/data/814375/0000814375-13-000043.txt,ALLIANCE ONE,COM,018772103,30720.0,8084091.0,SH,None,DFND,2,0.0,6223494.0,0.0
3,0000814375,"DONALD SMITH & CO., INC.",13F-HR,2013-06-30,2013-08-14,edgar/data/814375/0000814375-13-000043.txt,ALLIED NEVADA,COM,019344100,981.0,151350.0,SH,None,DFND,2,0.0,151350.0,0.0
4,0000814375,"DONALD SMITH & CO., INC.",13F-HR,2013-06-30,2013-08-14,edgar/data/814375/0000814375-13-000043.txt,AMERICAN INTERNATIONAL GROUP,COM,026874784,100204.0,2241694.0,SH,None,DFND,2,0.0,1600494.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172716,0001791786,Elliott Investment Management L.P.,13F-HR,2022-09-30,2022-11-14,edgar/data/1791786/0001567619-22-020034.txt,WESTERN DIGITAL CORP.,COM,958102105,38572.0,1185000.0,SH,None,DFND,"01,02",0.0,1185000.0,0.0
172717,0001791786,Elliott Investment Management L.P.,13F-HR,2022-09-30,2022-11-14,edgar/data/1791786/0001567619-22-020034.txt,CLARIVATE PLC,ORD SHS,G21810109,93900.0,10000000.0,SH,None,DFND,"01,02",0.0,10000000.0,0.0
172718,0001791786,Elliott Investment Management L.P.,13F-HR,2022-09-30,2022-11-14,edgar/data/1791786/0001567619-22-020034.txt,NIELSEN HLDGS PLC,SHS EUR,G6518L108,460152.0,16600000.0,SH,None,DFND,"01,02",0.0,16600000.0,0.0
172719,0001791786,Elliott Investment Management L.P.,13F-HR,2022-09-30,2022-11-14,edgar/data/1791786/0001567619-22-020034.txt,NOBLE CORP NEW,ORD SHS A,G65431127,84303.0,2850000.0,SH,None,DFND,"01,02",0.0,2850000.0,0.0
172720,0001791786,Elliott Investment Management L.P.,13F-HR,2022-09-30,2022-11-14,edgar/data/1791786/0001567619-22-020034.txt,VALARIS LIMITED,CL A,G9460G101,168843.0,3450000.0,SH,None,DFND,"01,02",0.0,3450000.0,0.0

In [25]:
#show all sshprnamt sorted by size starting from smallest
mngrdata.sort_values(by='fdate', ascending=True)

,cik,coname,form,rdate,fdate,fname,nameofissuer,titleofclass,cusip,value,sshprnamt,sshprnamttype,putcall,investmentdiscretion,othermanager,sole,shared,none
5187,0001037389,RENAISSANCE TECHNOLOGIES LLC,13F-HR,2013-06-30,2013-08-12,edgar/data/1037389/0001037389-13-000057.txt,MERIDIAN INTERSTAT BANCORP I,COM,58964Q104,1.286000e+03,68300.0,SH,None,SOLE,0,68300.0,0.0,0.0
4900,0001037389,RENAISSANCE TECHNOLOGIES LLC,13F-HR,2013-06-30,2013-08-12,edgar/data/1037389/0001037389-13-000057.txt,INTERNATIONAL TOWER HILL MIN,COM,46050R102,3.620000e+02,557100.0,SH,None,SOLE,0,93000.0,0.0,464100.0
4899,0001037389,RENAISSANCE TECHNOLOGIES LLC,13F-HR,2013-06-30,2013-08-12,edgar/data/1037389/0001037389-13-000057.txt,INTERNATIONAL SHIPHOLDING CO,COM NEW,460321201,5.672000e+03,243100.0,SH,None,SOLE,0,230698.0,0.0,12402.0
4898,0001037389,RENAISSANCE TECHNOLOGIES LLC,13F-HR,2013-06-30,2013-08-12,edgar/data/1037389/0001037389-13-000057.txt,INTERNATIONAL BUSINESS MACHS,COM,459200101,2.110050e+05,1104100.0,SH,None,SOLE,0,1104100.0,0.0,0.0
4897,0001037389,RENAISSANCE TECHNOLOGIES LLC,13F-HR,2013-06-30,2013-08-12,edgar/data/1037389/0001037389-13-000057.txt,INTERNAP NETWORK SVCS CORP,COM PAR $.001,45885A300,9.380000e+02,113400.0,SH,None,SOLE,0,113400.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159419,0001067983,BERKSHIRE HATHAWAY INC,13F-HR,2023-06-30,2023-08-14,edgar/data/1067983/0000950123-23-008074.txt,LIBERTY MEDIA CORP DEL,COM SER C FRMLA,531229854,3.880692e+07,515501.0,SH,None,DFND,"4,8,11",515501.0,0.0,0.0
159420,0001067983,BERKSHIRE HATHAWAY INC,13F-HR,2023-06-30,2023-08-14,edgar/data/1067983/0000950123-23-008074.txt,LIBERTY MEDIA CORP DEL,COM SER C FRMLA,531229854,9.441618e+06,125420.0,SH,None,DFND,"4,11",125420.0,0.0,0.0
159421,0001067983,BERKSHIRE HATHAWAY INC,13F-HR,2023-06-30,2023-08-14,edgar/data/1067983/0000950123-23-008074.txt,LOUISIANA PAC CORP,COM,546347105,2.024460e+08,2700000.0,SH,None,DFND,4,2700000.0,0.0,0.0
159339,0001067983,BERKSHIRE HATHAWAY INC,13F-HR,2023-06-30,2023-08-14,edgar/data/1067983/0000950123-23-008074.txt,BANK AMER CORP,COM,060505104,8.944968e+09,311780000.0,SH,None,DFND,"4,8,11",311780000.0,0.0,0.0
153262,0001056823,HORIZON KINETICS ASSET MANAGEMENT LLC,13F-HR,2023-06-30,2023-08-14,edgar/data/1056823/0001056823-23-000044.txt,COSTAMARE INC SHS,SHS,Y1771G102,2.207990e+06,228334.0,SH,None,DFND,None,228334.0,0.0,0.0

In [26]:
# reset f-date to datetime format and make sure all the values are in the first day of the month
def adjust_dates(group, threshold=3):
    # Sort dates
    sorted_dates = group.sort_values()
    # Initialize a new list to hold adjusted dates
    adjusted_dates = []
    
    # Use the first date as the starting point
    current_date = sorted_dates.iloc[0]
    
    for date in sorted_dates:
        # If the date is within the threshold, assign it to the current grouping date
        if (date - current_date).days <= threshold:
            adjusted_dates.append(current_date)
        else:
            # Update the current_date and add to adjusted_dates
            current_date = date
            adjusted_dates.append(current_date)
    
    # Return the adjusted dates corresponding to the original dates
    return pd.Series(adjusted_dates, index=group.index)

# Apply the function to each 'cik' group
mngrdata['adjusted_fdate'] = mngrdata.groupby('cik')['fdate'].transform(adjust_dates)

# get unique fdate count for each unique cik
# x-axis is cik, y-axis is fdate and datapoints are counts of fdate in our table
cik_fdate = mngrdata.pivot_table(index='cik', columns='adjusted_fdate', aggfunc='size', fill_value=0)

In [27]:
cik_fdate

adjusted_fdate,2013-08-12,2013-08-14,2013-08-15,2013-11-13,2013-11-14,2013-11-25,2014-02-07,2014-02-12,2014-02-13,2014-02-14,...,2023-02-09,2023-02-13,2023-02-14,2023-05-12,2023-05-15,2023-05-16,2023-05-17,2023-08-10,2023-08-11,2023-08-14
cik,,,,,,,,,,,,,,,,,,,,,
0000814375,0,91,0,85,0,0,80,0,80,0,...,66,0,0,0,0,0,64,62,0,0
0001037389,2756,0,0,2781,0,0,0,0,0,2816,...,0,4073,0,3924,0,0,0,0,3864,0
0001050464,0,60,0,0,76,0,0,73,0,0,...,0,0,33,0,34,0,0,0,0,16
0001056823,0,0,0,0,0,0,0,0,0,0,...,0,0,0,329,0,0,0,0,0,329
0001067983,0,0,127,0,133,0,0,0,0,137,...,0,0,172,0,165,0,0,0,0,157
0001079114,0,95,0,0,95,3,0,0,0,119,...,0,0,123,0,114,0,0,0,0,122
0001169883,0,56,0,0,60,0,0,0,0,61,...,0,0,29,0,34,0,0,0,0,38
0001336528,0,18,0,0,15,0,0,0,0,7,...,0,6,0,0,8,0,0,0,0,8
0001536411,0,34,0,0,28,0,0,0,0,42,...,0,0,57,0,48,0,0,0,0,53
0001541617,0,30,0,0,33,0,0,0,0,35,...,0,0,11,0,0,11,0,0,0,11
0001541901,0,43,0,0,36,0,0,0,0,46,...,0,0,51,0,54,0,0,0,0,48
0001553733,0,11,0,0,11,0,0,0,0,14,...,0,0,26,0,28,0,0,0,0,32
0001649339,0,0,0,0,0,0,0,0,0,0,...,0,0,9,0,21,0,0,0,0,31
0001657335,0,0,0,0,0,0,0,0,0,0,...,0,0,8,0,8,0,0,0,0,9
0001791786,0,0,0,0,0,0,0,0,0,0,...,0,0,44,0,84,0,0,0,0,44

In [2]:
crsp_data = load_wrds.load_daily_stock_returns()
crsp_data.to_parquet(DATA_DIR / "Pulled" / "crsp_data.parquet")

Loading library list...
Done